import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavbarWrapper from "./components/NavbarWrapper"
import { ThemeProvider } from "./components/theme-provider"
import { SessionProviderWrapper } from "./components/session-provider"
import FloatingAIChat from "./components/FloatingAIChat"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} min-h-screen bg-gradient-to-br from-slate-50 via-slate-100 to-slate-50 text-slate-900 antialiased dark:bg-gradient-to-br dark:from-slate-950 dark:via-slate-900 dark:to-slate-950 dark:text-slate-100`}
      >
        <SessionProviderWrapper>
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
            <NavbarWrapper />
            <main className="min-h-screen w-full pt-16">
              {children}
            </main>
            <FloatingAIChat />
          </ThemeProvider>
        </SessionProviderWrapper>
      </body>
    </html>
  );
}
